;--------------------------------------------------------------------------------
; winPenPack Project – X-Software collection
; X-Launcher 1.5.4 Copyright © Gabriele Tittonel and winPenPack Development Team
;
; Configurazione per Submarine
; by Daniele Lolli (UncleDan) feat. Claude AI - Release 1.0 - 2026-09-27 16:09:04
;--------------------------------------------------------------------------------
[Version]
Ini Author=Daniele Lolli
Ini Revision=1
Ini Rev.Author=Daniele Lolli
Ini Date=27/09/2026
Ini Locale=it
Software=Submarine
Soft.Author=
Soft.Version=
Web=https://github.com/SinaXhpm/Submarine
Launcher=1.5.4
System=

[Group]
Category=
Sub Category=
License=
;--------------------------------------------------------------------------------

[Setup]
AppName=Submarine
Profile=Default

[FileToRun]
PathToExe=$Bin$\$AppName$\Submarine.exe
Parameters=

[Environment]
;(redirect del profilo utente dell'app)
USERPROFILE=$Home$\$AppName$\Profile
APPDATA=$Home$\$AppName$\AppData\Roaming
LOCALAPPDATA=$Home$\$AppName$\AppData\Local

[FirstRunOperations]
;(al primo avvio, se Submarine.exe manca ancora, scarica ed estrae l'app)
RunFile=$Bin$\$AppName$\Init_Submarine.bat

[Options]
DeleteTemp=true
MultipleIstances=false
RunWait=true
ShowSplash=false
WriteLog=false
FirstRun=true
ShowTrayTip=false

[SplashScreen]
Image=
Title=
TimeOut=1500
