[Environment]
; Reindirizzamento per rendere il programma portabile
USERPROFILE=$User$\Submarine\Profile
APPDATA=$User$\Submarine\AppData\Roaming
LOCALAPPDATA=$User$\Submarine\AppData\Local

[RunBefore]
; Verifica se Submarine.exe e' presente; se manca, avvia il download/estrazione
Exe=wscript.exe
Parameters="$Bin$\Submarine\CheckFirstRun.vbs"
Wait=true

[Run]
; Viene eseguito solo dopo che il [RunBefore] ha terminato
Exe=$Bin$\Submarine\Submarine.exe
Parameters=
WorkingDirectory=$Bin$\Submarine
